--[==[
				    ___    ____  ________
				   /   |  / __ \/  _/ __ \___
				  / /| | / /_/ // // / / / _ \
				 / ___ |/ _, _// // /_/ /  __/
				/_/  |_/_/ |_/___/_____/\___/
                  For lack of a better name.

		@Description: Astra Remote Integrated Defense | MainModule
		@Author: EasternBloxxer
		@Date of Creation: 12th April, 2019 | Powered by Latte
]==]--

return require(script.Server.Server)