name: rojo
 
on:
  push:
    branches: [main]
    tags: 
      - v**
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      
      - name: Layout file name
        id: naming
        env:
          GIT_HASH: ${{ github.sha }}
          GITHUB_REPO: ${{ github.repository }}
          GIT_REF: ${{ github.ref_name }}
          GIT_REF_TYPE: ${{ github.ref_type }}
          GITHUB_ACTION_EVENT_NAME: ${{ github.event_name }}
          GITHUB_IS_PRE_RELEASE: ${{ github.event_name  == 'release' && github.event.isPrerelease }}
        run: |
         CUR_DATE_TIME=$(date +'%Y-%m-%d')
         if [ "$GITHUB_ACTION_EVENT_NAME" == "push" ] && [ "$GIT_REF" == "release" ]
         then
           BUILD_TYPE="DebugStable"
         elif [ "$GITHUB_ACTION_EVENT_NAME" == "push" ] &&  [ "$GIT_REF_TYPE" == "tag" ]
          then
            BUILD_TYPE="DebugRelease"
         elif [ "$GITHUB_ACTION_EVENT_NAME" == "release" ] && [ "$GITHUB_IS_PRE_RELEASE" == "false" ]
          then
            BUILD_TYPE="DebugRelease"
         elif [ "$GITHUB_ACTION_EVENT_NAME" == "release" ] && [ "$GITHUB_IS_PRE_RELEASE" == "true" ]
          then
            BUILD_TYPE="DebugBeta"
         elif [ "$GITHUB_ACTION_EVENT_NAME" == "pull_request" ] || [ "$GITHUB_REPO" != "Epix-Incorporated/Adonis" ]
         then
           BUILD_TYPE="PRSnapshot"
         else
           BUILD_TYPE="Nightly"
         fi
         echo "output_name=Adonis_${BUILD_TYPE}_${CUR_DATE_TIME}_$(git rev-parse --short "$GIT_HASH")" >> $GITHUB_OUTPUT

      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: rojo build -o ${{ steps.naming.outputs.output_name }}.rbxm .github/build.project.json

      - uses: actions/upload-artifact@v4.3.6
        with:
          name: ${{ steps.naming.outputs.output_name }}
          path: ${{ steps.naming.outputs.output_name }}.rbxm

    # The following commands are run for pushes only.
          
      - name: Build Nightly MainModule
        if: github.repository == 'Astra-Corporation/Astra.Admin' && github.event_name == 'push' && github.ref_name == 'main'
        run: rojo build -o module.rbxm .github/module.deploy.project.json

      - name: Send file nightly build to Discord channel
        uses: tsickert/discord-webhook@v6.0.0
        if: github.repository == 'Astra-Corporation/Astra.Admin' && github.event_name == 'push' && github.ref_name == 'main'
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK }}
          filename: ${{ steps.naming.outputs.output_name }}.rbxm