name: rojo

on:
  push:
    branches: [master,dev,Ender/Rewrite-1,version-2.5.0]
  pull_request:
    branches: [master,dev,Ender/Rewrite-1,version-2.5.0]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: rojo build -o Astra_Nightly_${{ steps.date.outputs.date }}.rbxm .github/build.project.json

      - uses: actions/upload-artifact@v2
        with:
          name: Astra_Nightly_${{ steps.date.outputs.date }}
          path: Astra_Nightly_${{ steps.date.outputs.date }}.rbxm
          
      - name: Build Nightly MainModule
        if: github.repository == 'Astra-Corporation/ARIDe' && github.event_name == 'push'
        run: rojo build -o module.rbxm .github/module.deploy.project.json
      - name: Send file nightly build to Discord channel
        uses: tsickert/discord-webhook@v3.0.0
        if: github.repository == 'Astra-Corporation/ARIDe' && github.event_name == 'push'
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK }}
          filename: Astra_Nightly_${{ steps.date.outputs.date }}.rbxm
          content: ""
